ddp:
    master_addr: "localhost"
    master_port: "29501"
    num_devices: 2

rlbench:
    task_name: "single"
    tasks: [press_handsan]
    demos: 1 #10
    demo_path: /home/bepgroup/BEPproject/peract/real_world_data
    episode_length: 25
    cameras: ['front']
    camera_resolution: [128,128]
    scene_bounds: [-0.3, -0.5, 0.6, 0.7, 0.5, 1.6]
    include_lang_goal_in_obs: True

replay:
    batch_size: 1
    timesteps: 1
    prioritisation: False
    task_uniform: False # uniform sampling of tasks for multi-task buffers
    use_disk: True
    path: '/home/bepgroup/BEPproject/training_log/replay' # only used when use_disk is True.
    max_parallel_processes: 16

framework:
    log_freq: 100
    save_freq: 100
    train_envs: 1
    replay_ratio: ${replay.batch_size}
    transitions_before_train: 200
    tensorboard_logging: True
    csv_logging: True
    training_iterations: 2400
    gpu: 0
    env_gpu: 0
    logdir: '/home/bepgroup/BEPproject/training_log'
    logging_level: 20 # https://docs.python.org/3/library/logging.html#levels
    seeds: 1
    start_seed: 11
    load_existing_weights: False
    num_weights_to_keep: 60 # older checkpoints will be deleted chronologically
    num_workers: 0
    record_every_n: 5

defaults:
    - method: PERACT_BC

hydra:
    run:
        dir: ${framework.logdir}/${rlbench.task_name}/${method.name}
